:global:
  componentName: openshift4-registry
  githubUrl: https://github.com/appuio/component-openshift4-registry
  feature_goldenTests: true

docs/antora.yml:
  name: openshift4-registry
  title: OpenShift 4 Registry

.github/workflows/test.yaml:
  test_makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
  matrix:
    key: instance
    entries:
      - defaults
      - minimal
