:global:
  componentName: OpenShift 4 Registry
  githubUrl: https://github.com/appuio/component-openshift4-registry
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - minimal

.github/workflows/test.yaml:
  test_makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
